export const teachers= [
    {
      id: '1',
      name: 'John Nguyen',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'john.nguyen@university.edu',
      phone: '0901234567',
      gender: 'Male',
      roles: ['Lecturer', 'Curriculum Advisor'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Mathematics', 'Statistics'],
    },
    {
      id: '2',
      name: 'Linh Tran',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'linh.tran@university.edu',
      phone: '0912345678',
      gender: 'Female',
      roles: ['Lecturer', 'Academic Mentor'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Literature', 'Creative Writing'],
    },
    {
      id: '3',
      name: 'Michael Pham',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'michael.pham@university.edu',
      phone: '0938765432',
      gender: 'Male',
      roles: ['Senior Lecturer', 'Researcher'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Physics', 'Computer Science'],
    },
    {
      id: '4',
      name: 'Sophia Le',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'sophia.le@university.edu',
      phone: '0945678910',
      gender: 'Female',
      roles: ['Assistant Professor', 'Event Coordinator'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Chemistry', 'Biology'],
    },
    {
      id: '5',
      name: 'David Hoang',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'david.hoang@university.edu',
      phone: '0909090909',
      gender: 'Male',
      roles: ['Lecturer'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Philosophy', 'Sociology', 'Political Science'],
    },
    {
      id: '6',
      name: 'Emily Do',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'emily.do@university.edu',
      phone: '0923344556',
      gender: 'Female',
      roles: ['Lecturer', 'Advisor', 'Exam Supervisor'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['English', 'Public Speaking'],
    },
    {
      id: '7',
      name: 'Henry Vu',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'henry.vu@university.edu',
      phone: '0911223344',
      gender: 'Male',
      roles: ['Program Coordinator', 'Lecturer'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Software Engineering', 'Data Structures'],
    },
    {
      id: '8',
      name: 'Olivia Bui',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'olivia.bui@university.edu',
      phone: '0966889900',
      gender: 'Female',
      roles: ['Researcher', 'Senior Lecturer'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Genetics', 'Biochemistry'],
    },
    {
      id: '9',
      name: 'Alex Dang',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'alex.dang@university.edu',
      phone: '0977002233',
      gender: 'Male',
      roles: ['Lecturer', 'Class Advisor'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Database Systems', 'Algorithms'],
    },
    {
      id: '10',
      name: 'Grace Phan',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'grace.phan@university.edu',
      phone: '0955337788',
      gender: 'Female',
      roles: ['Lab Instructor', 'Lecturer'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Physics Lab', 'Electric Circuits'],
    },
    {
      id: '11',
      name: 'William Dinh',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'william.dinh@university.edu',
      phone: '0933221100',
      gender: 'Male',
      roles: ['Lecturer', 'Project Supervisor'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Machine Learning', 'AI'],
    },
    {
      id: '12',
      name: 'Natalie Tran',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'natalie.tran@university.edu',
      phone: '0944001122',
      gender: 'Female',
      roles: ['Lecturer', 'Department Secretary'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Marketing', 'Digital Media'],
    },
    {
      id: '13',
      name: 'Tommy Nguyen',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'tommy.nguyen@university.edu',
      phone: '0988001122',
      gender: 'Male',
      roles: ['Head of Department', 'Professor'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Economics', 'Finance'],
    },
    {
      id: '14',
      name: 'Anna Vu',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'anna.vu@university.edu',
      phone: '0922888899',
      gender: 'Female',
      roles: ['Lecturer'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['French', 'Linguistics'],
    },
    {
      id: '15',
      name: 'Daniel Pham',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'daniel.pham@university.edu',
      phone: '0966554433',
      gender: 'Male',
      roles: ['Teaching Assistant', 'Research Assistant'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Robotics', 'Mathematics'],
    },
    {
      id: '16',
      name: 'Jenny Nguyen',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'jenny.nguyen@university.edu',
      phone: '0911998877',
      gender: 'Female',
      roles: ['Lecturer', 'Curriculum Developer'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['History', 'Cultural Studies'],
    },
    {
      id: '17',
      name: 'Ryan Le',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'ryan.le@university.edu',
      phone: '0977332211',
      gender: 'Male',
      roles: ['Lecturer'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Mobile Development', 'Web Development'],
    },
    {
      id: '18',
      name: 'Hannah Bui',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'hannah.bui@university.edu',
      phone: '0955112233',
      gender: 'Female',
      roles: ['Senior Lecturer', 'Student Support Officer'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Psychology', 'Counseling'],
    },
    {
      id: '19',
      name: 'Ethan Ho',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'ethan.ho@university.edu',
      phone: '0900111122',
      gender: 'Male',
      roles: ['Lecturer', 'Club Advisor'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Music Theory', 'Art History'],
    },
    {
      id: '20',
      name: 'Victoria Tran',
      avatarUrl: 'https://st.nhipcaudautu.vn/staticFile/Subject/2022/02/25/space-x-elon-musk_251529404.jpeg',
      email: 'victoria.tran@university.edu',
      phone: '0933556677',
      gender: 'Female',
      roles: ['Lecturer', 'Training Manager'],
      description:'Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt elit laborum.',
      age: 34,
      subjects: ['Business Ethics', 'Human Resource Management'],
    },
  ];